apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app
  namespace: yourwheel-dev
  labels:
    app: consumer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
      - name: consumer-app
        image: stupin97/console-consumer-rabbitmq:1.0.2
        env:
        - name: EmailSettings__Host
          valueFrom:
            configMapKeyRef:
              name: consumer-config
              key: EmailSettings__Host
        - name: EmailSettings__Port
          valueFrom:
            configMapKeyRef:
              name: consumer-config
              key: EmailSettings__Port
        - name: EmailSettings__Username
          valueFrom:
            configMapKeyRef:
              name: consumer-config
              key: EmailSettings__Username
        - name: EmailSettings__AppPassword
          valueFrom:
            configMapKeyRef:
              name: consumer-config
              key: EmailSettings__AppPassword
        - name: RabbitMQ__HostName
          valueFrom:
            configMapKeyRef:
              name: consumer-config
              key: RabbitMQ__HostName
        - name: RabbitMQ__QueueName
          valueFrom:
            configMapKeyRef:
              name: consumer-config
              key: RabbitMQ__QueueName
        - name: RabbitMQ__ExchangeName
          valueFrom:
            configMapKeyRef:
              name: consumer-config
              key: RabbitMQ__ExchangeName
        - name: RabbitMQ__DefaultUser
          valueFrom:
            configMapKeyRef:
              name: consumer-config
              key: RabbitMQ__DefaultUser
        - name: RabbitMQ__DefaultPass
          valueFrom:
            configMapKeyRef:
              name: consumer-config
              key: RabbitMQ__DefaultPass
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 15
          periodSeconds: 10