apiVersion: v1
kind: Service
metadata:
  name: consumer-app
  namespace: yourwheel-dev
  labels:
    app: consumer-app
spec:
  selector:
    app: consumer-app
  ports:
  - protocol: TCP
    port: 82
    targetPort: 82
  type: ClusterIP