apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yourwheel-dev
configMapGenerator:
- name: consumer-config
  envs:
  - ./envs/consumer-config.env
resources:
  - consumer-deployment.yaml
  - consumer-service.yaml