version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    env_file:
      - ./YourWheel.Host/docker.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  your-wheel:
    container_name: your-wheel
    build:
      context: .
      dockerfile: YourWheel.Host/Dockerfile
      args:
        DB_HOST: db
    env_file:
      - ./YourWheel.Host/docker.env
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+;http://+
        - ASPNETCORE_HTTPS_PORT=5001
        - ASPNETCORE_Kestrel__Certificates__Default__Password=pass1111
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificates/aspnetapp.pfx
        #- DB_CONNECTION_STRING_POSTGRES=${DB_CONNECTION_STRING_POSTGRES}
        #- JWT_ISSUER=${JWT_ISSUER}
        #- JWT_AUDIENCE=${JWT_AUDIENCE}
        #- JWT_KEY=${JWT_KEY}
        #- JWT_LIFETIME=${JWT_LIFETIME}
        #- POSTGRES_USER=${POSTGRES_USER}
        #- POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        #- POSTGRES_DB=${POSTGRES_DB}
        #- DB_HOST=${DB_HOST}
    restart:
        always
    ports:
        - "5000:80"
        - "5001:443"
    networks:
       - default
    volumes:
       - /MicroService/.aspnet/https:/https/
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  default:
    driver: bridge