version: '3.8'

services:
  your-wheel:
    container_name: your-wheel
    build:
      context: .
      dockerfile: YourWheel.Host/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+;http://+
        - ASPNETCORE_HTTPS_PORT=5001
        - ASPNETCORE_Kestrel__Certificates__Default__Password=pass1111
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificates/aspnetapp.pfx
        - DB_CONNECTION_STRING_POSTGRES=${DB_CONNECTION_STRING_POSTGRES}
        - JWT_ISSUER=${JWT_ISSUER}
        - JWT_AUDIENCE=${JWT_AUDIENCE}
        - JWT_KEY=${JWT_KEY}
        - JWT_LIFETIME=${JWT_LIFETIME}
    restart:
        always
    ports:
        - "5000:80"
        - "5001:443"
    networks:
       - default
    volumes:
       - /MicroService/.aspnet/https:/https/