apiVersion: v1
kind: Service
metadata:
  name: your-wheel
  namespace: yourwheel-dev
  labels:
    app: your-wheel
spec:
  selector:
    app: your-wheel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  type: ClusterIP